[build]
  base    = "client"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "client/build"

[build.environment]
  DISABLE_ESLINT_PLUGIN   = "true"
  ESLINT_NO_DEV_ERRORS    = "true"
  GENERATE_SOURCEMAP      = "false"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
